spring:
  application:
    name: oficinarrhh-service
server:
  port: 8005
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}